lenguage: node_js
cache:
  directories:
    - node_modules
    - ~/.npm
node_js:
  - '12'
git:
 depth: 3
script:
  - yarn test
  - gems install ruby 2.6
notifications:
  email:
    recipients:
      - josebrusa@outlook.com
    on_success: always
    on_failure: always
deploy:
  provider: heroku
  api_key: ff90c81e-47d6-4cd8-b26c-8eaf75738059
  app: store-backplatzi
  skip-cleanup: true
  keep-history: true
  on:
    repo: josebrusa/platzi-store-backend
