lenguage: node_js
cache:
  directories:
    - node_modules
    - ~/.npm
node_js:
  - '12'
git:
 depth: 3
script:
  - yarn test
before_install:
  - sudo apt-get update
  - sudo apt-get -y install libxml2-dev
notifications:
  email:
    recipients:
      - josebrusa@outlook.com
    on_success: always
    on_failure: always
deploy:
  provider: heroku
  api_key:
    secure: e478af88-3b4a-4539-aa00-c9134a58ac75
  app: store-backplatzi
  skip-cleanup: true
  keep-history: true
  on:
    repo: josebrusa/platzi-store-backend
